apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      component: wordpress-app
  template:
    metadata:
      labels:
        component: wordpress-app
    spec:
      containers:
        - image: wordpress:6.6.2-apache
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: gapai-blog-db-service
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gapai-blog-env
                  key: DB_PASSWORD
            - name: WORDPRESS_DB_USER
              value: wordpress
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: gapai-blog-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: app-persistent-storage
          persistentVolumeClaim:
            claimName: app-pv-claim