apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
#  type: ClusterIP
#  ports:
#    - port: 80
#      targetPort: 80
#  selector:
#    app: blog // un-work type ClusterIP
  ports:
    - port: 80
  selector:
    component: wordpress-app
  type: LoadBalancer
