version: "3.8"
services:
  app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: always
    command: npm run dev
    env_file:
      - .env.example
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
