name: "CI"
on:
  pull_request:
  push:
    branches:
      - main

env:
  SHA: ${{ github.sha }}
  GKE_CLUSTER: deploy-learn
  GKE_ZONE: asia-southeast1-b

jobs:
  build_push:
    name: "Build & Push Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Push"
        run: |
          docker build -t agung96tm/next-js-app:latest -t agung96tm/next-js-app:$SHA -f Dockerfile .
          docker push agung96tm/next-js-app:$SHA
        env:
          SHA: ${{ env.SHA }}

  deploy:
    name: "Deploy to Cluster"
    runs-on: ubuntu-latest
    needs: [ build_push ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: 'Deploy to GKE'
        run: |
          kubectl apply -f k8s
          kubectl set image deployment/server-deployment app=agung96tm/next-js-app:$SHA
        env:
          SHA: ${{ env.SHA }}