apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: angular-app
  template:
    metadata:
      labels:
        component: angular-app
      containers:
        - name: app
          image: agung96tm/angular-app
          ports:
            - containerPort: 3000
          env:
            - name: APP_URL
              value: 'https://www.linkedin.com/in/agung96tm'
