version: "3.8"
services:
  app:
    container_name: angular-app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: always
    command: npm run start:dev
    env_file:
      - .env.example
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
      - /app/.angular
    ports:
      - "4200:4200"
