apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-js-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: next-js-app
  template:
    metadata:
      labels:
        component: next-js-app
      containers:
        - name: app
          image: agung96tm/next-js-app
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_APP_URL
              value: 'https://www.linkedin.com/in/agung96tm'
